<a href="https://colab.research.google.com/github/Saisneha0209/Own-Practise/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
s = pd.Series([10,20,30,40,50,60])
print(s)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [6]:
s.dtype

dtype('int64')

In [7]:
s.values

array([10, 20, 30, 40, 50, 60])

In [9]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [10]:
print(s.name)

None

In [31]:
s.name = "Calories"

In [32]:
s

0    10
1    20
2    30
3    40
4    50
5    60
Name: Calories, dtype: int64

In [14]:
a = pd.Series([10,20,30,40,50,60])
print(a)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [21]:
a.index

RangeIndex(start=0, stop=6, step=1)

In [22]:
a.values

array([10, 20, 30, 40, 50, 60])

In [23]:
a.name = "AGAIN NUMBERS"

In [24]:
a

0    10
1    20
2    30
3    40
4    50
5    60
Name: AGAIN NUMBERS, dtype: int64

In [25]:
#INDEXING!!
s[1]

np.int64(20)

In [26]:
a[0]

np.int64(10)

In [27]:
s[0:2]

0    10
1    20
Name: Numbers, dtype: int64

In [28]:
s[2:4]

2    30
3    40
Name: Numbers, dtype: int64

In [29]:
#iloc :- Location - Based Indexing!!
s.iloc[3]

np.int64(40)

In [30]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: Numbers, dtype: int64

In [34]:
index = ['apple','banana','grapes','pineapple','tomato','potato']
s.index = index
s

apple        10
banana       20
grapes       30
pineapple    40
tomato       50
potato       60
Name: Calories, dtype: int64

In [38]:
s.loc['grapes']

np.int64(30)

In [37]:
#loc -.label - based indexing!!

In [39]:
#In label based indexing your start as well as stop values both are included in the output!!

In [41]:
s['banana':'potato']

banana       20
grapes       30
pineapple    40
tomato       50
potato       60
Name: Calories, dtype: int64

In [42]:
s.loc[['grapes','banana','potato']]

grapes    30
banana    20
potato    60
Name: Calories, dtype: int64

In [44]:
fruit_protein = {"avocado":567,
                 "Guava":345,
                 "potato":456,
                 "orange":789,
                 "berry":456,
                 "perry":420}

In [47]:
s2 = pd.Series(fruit_protein, name = "Protein")

In [48]:
s2

avocado    567
Guava      345
potato     456
orange     789
berry      456
perry      420
Name: Protein, dtype: int64

In [52]:
#CONDITIONAL SELECTION:-
s2[s2>500]

avocado    567
orange     789
Name: Protein, dtype: int64

In [53]:
#LOGICAL OPERATORS :-
#AND and OR....
#notnull() gives a bracket of values which are not null..
#and sum gives the number of the list as per the 0 and 1 assigned to them!!

In [55]:
#df = pd.read("given data name")
#df.head(10)
#df.tail(5)

In [56]:
#loc and iloc

In [57]:
#df.iloc[1:3]
#df.loc[1:2,['age','department]]
#df.['Age']
#df.drop("Age",axis = 1,inplace = True)1 is for that column and axis = 0 is for a particular row to be gone!!
#inplace means performing operations in out original data!!otherwise by default it is false..
#df.shape()
#df.info()
#df.describe()

In [59]:
#BroadCasting!!
#df.rename = (columns = {"department":"age"}, inplace = True)
#df.unique() to check the values that are unique in your data!!

In [60]:
#df["column name"].value_counts() this means there are how many things in a particular column..

In [62]:
#DATA - CLEANING!!
#df.isnull().sum()
#IF WE FIND ANY TYPE OF NULL VALUES IN THE DATA EITHER WE CAN DROP IT OR EITHER WE CAN FILL IT WITH THE MOST REPEATED VALUES OR EITHER WE HAVE TO PASS THAT ARGUMENT TO THAT IN FILL.NA(0)
#df.dropna(how ="any") #which ever row has any null values it will drop out!!
#df.fillna(0) THIS WILL FILL OUT THE COLUMN WHICHEVER HAS THE NULL VALUES!!

In [63]:
#DF ["AGE"].FILLNA(method = "ffill")
#there are forward fill and then the backward fill soo forward mai agae usse pehla vala hoghga toh vo value and
#in backward fill jo null value ke baad vala hoga uski value will be placed there!!

In [64]:
#df_dup = df[df.duplicated(keep = "last")]
#df_dup
#df = df.drop_duplicates()
#lamda function!!

In [65]:
#str.split("_")

In [65]:
#pd.concat([df,df2])